# Generated by Django 4.0.3 on 2022-04-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='my blog', max_length=255),
        ),
    ]
